// SÓLO DATOS. Palabras del "Código Aura" (la competencia de aura: leer 3 palabras y elegir sus figuras en el criptex).
// Palabras concretas, que se puedan dibujar, de 3 sílabas o más, en español de Chile.
//   id         la palabra, sin tildes ni eñes (y el nombre de su imagen: assets/criptex/<id>.png, cuando exista)
//   palabra    como se escribe y se muestra
//   silabas    separadas, para la ayuda del nivel fácil
//   emoji      imagen provisoria mientras no esté la propia
//   parecidas  ids de palabras que empiezan igual o se parecen: son los distractores de su anillo (así no basta con
//              mirar la primera letra)
// (Sin "botella": no hay un emoji claro; vuelve cuando esté el set de imágenes propio.)
export const PALABRAS = [
  { id: 'canguro', palabra: 'canguro', silabas: ['can', 'gu', 'ro'], emoji: '🦘', parecidas: ['cangrejo', 'caracol', 'camello', 'caballo'] },
  { id: 'cangrejo', palabra: 'cangrejo', silabas: ['can', 'gre', 'jo'], emoji: '🦀', parecidas: ['canguro', 'caracol', 'camello'] },
  { id: 'caracol', palabra: 'caracol', silabas: ['ca', 'ra', 'col'], emoji: '🐌', parecidas: ['caramelo', 'camello', 'canguro', 'cangrejo'] },
  { id: 'caramelo', palabra: 'caramelo', silabas: ['ca', 'ra', 'me', 'lo'], emoji: '🍬', parecidas: ['caracol', 'camello', 'calcetin'] },
  { id: 'camello', palabra: 'camello', silabas: ['ca', 'me', 'llo'], emoji: '🐫', parecidas: ['caballo', 'caracol', 'canguro', 'camisa'] },
  { id: 'caballo', palabra: 'caballo', silabas: ['ca', 'ba', 'llo'], emoji: '🐴', parecidas: ['camello', 'calcetin', 'castillo'] },
  { id: 'camisa', palabra: 'camisa', silabas: ['ca', 'mi', 'sa'], emoji: '👕', parecidas: ['camello', 'caramelo', 'calcetin'] },
  { id: 'calcetin', palabra: 'calcetín', silabas: ['cal', 'ce', 'tín'], emoji: '🧦', parecidas: ['camisa', 'caballo', 'caracol'] },
  { id: 'castillo', palabra: 'castillo', silabas: ['cas', 'ti', 'llo'], emoji: '🏰', parecidas: ['caballo', 'camello', 'calcetin'] },
  { id: 'cuchara', palabra: 'cuchara', silabas: ['cu', 'cha', 'ra'], emoji: '🥄', parecidas: ['cuaderno', 'castillo', 'caballo'] },
  { id: 'cuaderno', palabra: 'cuaderno', silabas: ['cua', 'der', 'no'], emoji: '📓', parecidas: ['cuchara', 'castillo', 'caballo'] },
  { id: 'pelota', palabra: 'pelota', silabas: ['pe', 'lo', 'ta'], emoji: '⚽', parecidas: ['pescado', 'pepino', 'paloma'] },
  { id: 'pescado', palabra: 'pescado', silabas: ['pes', 'ca', 'do'], emoji: '🐟', parecidas: ['pelota', 'pepino', 'pinguino'] },
  { id: 'pepino', palabra: 'pepino', silabas: ['pe', 'pi', 'no'], emoji: '🥒', parecidas: ['pelota', 'pescado', 'pinguino'] },
  { id: 'pinguino', palabra: 'pingüino', silabas: ['pin', 'güi', 'no'], emoji: '🐧', parecidas: ['pepino', 'pelota', 'pescado'] },
  { id: 'platano', palabra: 'plátano', silabas: ['plá', 'ta', 'no'], emoji: '🍌', parecidas: ['pelota', 'paloma', 'payaso'] },
  { id: 'estrella', palabra: 'estrella', silabas: ['es', 'tre', 'lla'], emoji: '⭐', parecidas: ['escoba', 'escalera', 'esponja'] },
  { id: 'escoba', palabra: 'escoba', silabas: ['es', 'co', 'ba'], emoji: '🧹', parecidas: ['estrella', 'esponja', 'escalera'] },
  { id: 'esponja', palabra: 'esponja', silabas: ['es', 'pon', 'ja'], emoji: '🧽', parecidas: ['escoba', 'estrella', 'escalera'] },
  { id: 'escalera', palabra: 'escalera', silabas: ['es', 'ca', 'le', 'ra'], emoji: '🪜', parecidas: ['escoba', 'estrella', 'esponja'] },
  { id: 'elefante', palabra: 'elefante', silabas: ['e', 'le', 'fan', 'te'], emoji: '🐘', parecidas: ['estrella', 'escoba', 'helado'] },
  { id: 'mariposa', palabra: 'mariposa', silabas: ['ma', 'ri', 'po', 'sa'], emoji: '🦋', parecidas: ['manzana', 'maleta', 'mandarina', 'mochila'] },
  { id: 'manzana', palabra: 'manzana', silabas: ['man', 'za', 'na'], emoji: '🍎', parecidas: ['mariposa', 'maleta', 'mandarina'] },
  { id: 'maleta', palabra: 'maleta', silabas: ['ma', 'le', 'ta'], emoji: '🧳', parecidas: ['manzana', 'mariposa', 'mochila'] },
  { id: 'mandarina', palabra: 'mandarina', silabas: ['man', 'da', 'ri', 'na'], emoji: '🍊', parecidas: ['manzana', 'maleta', 'mariposa'] },
  { id: 'mochila', palabra: 'mochila', silabas: ['mo', 'chi', 'la'], emoji: '🎒', parecidas: ['mariposa', 'maleta', 'manzana'] },
  { id: 'tortuga', palabra: 'tortuga', silabas: ['tor', 'tu', 'ga'], emoji: '🐢', parecidas: ['tomate', 'tornillo', 'telefono'] },
  { id: 'tomate', palabra: 'tomate', silabas: ['to', 'ma', 'te'], emoji: '🍅', parecidas: ['tortuga', 'tornillo', 'tijeras'] },
  { id: 'tornillo', palabra: 'tornillo', silabas: ['tor', 'ni', 'llo'], emoji: '🔩', parecidas: ['tortuga', 'tomate', 'tiburon'] },
  { id: 'tijeras', palabra: 'tijeras', silabas: ['ti', 'je', 'ras'], emoji: '✂️', parecidas: ['tiburon', 'tomate', 'tortuga'] },
  { id: 'tiburon', palabra: 'tiburón', silabas: ['ti', 'bu', 'rón'], emoji: '🦈', parecidas: ['tijeras', 'tortuga', 'tomate'] },
  { id: 'telefono', palabra: 'teléfono', silabas: ['te', 'lé', 'fo', 'no'], emoji: '📞', parecidas: ['tomate', 'tortuga', 'tiburon'] },
  { id: 'helado', palabra: 'helado', silabas: ['he', 'la', 'do'], emoji: '🍦', parecidas: ['elefante', 'helicoptero', 'hamburguesa'] },
  { id: 'helicoptero', palabra: 'helicóptero', silabas: ['he', 'li', 'cóp', 'te', 'ro'], emoji: '🚁', parecidas: ['helado', 'hamburguesa', 'elefante'] },
  { id: 'hamburguesa', palabra: 'hamburguesa', silabas: ['ham', 'bur', 'gue', 'sa'], emoji: '🍔', parecidas: ['helado', 'helicoptero', 'hormiga'] },
  { id: 'hormiga', palabra: 'hormiga', silabas: ['hor', 'mi', 'ga'], emoji: '🐜', parecidas: ['hamburguesa', 'helado', 'abeja'] },
  { id: 'jirafa', palabra: 'jirafa', silabas: ['ji', 'ra', 'fa'], emoji: '🦒', parecidas: ['gallina', 'galleta', 'guitarra'] },
  { id: 'gallina', palabra: 'gallina', silabas: ['ga', 'lli', 'na'], emoji: '🐔', parecidas: ['galleta', 'guitarra', 'jirafa'] },
  { id: 'galleta', palabra: 'galleta', silabas: ['ga', 'lle', 'ta'], emoji: '🍪', parecidas: ['gallina', 'guitarra', 'jirafa'] },
  { id: 'guitarra', palabra: 'guitarra', silabas: ['gui', 'ta', 'rra'], emoji: '🎸', parecidas: ['gallina', 'galleta', 'jirafa'] },
  { id: 'zapato', palabra: 'zapato', silabas: ['za', 'pa', 'to'], emoji: '👞', parecidas: ['zanahoria', 'sandia', 'sirena'] },
  { id: 'zanahoria', palabra: 'zanahoria', silabas: ['za', 'na', 'ho', 'ria'], emoji: '🥕', parecidas: ['zapato', 'sandia', 'sombrero'] },
  { id: 'sandia', palabra: 'sandía', silabas: ['san', 'dí', 'a'], emoji: '🍉', parecidas: ['zanahoria', 'zapato', 'sirena'] },
  { id: 'sirena', palabra: 'sirena', silabas: ['si', 're', 'na'], emoji: '🧜‍♀️', parecidas: ['sandia', 'sombrero', 'serpiente'] },
  { id: 'serpiente', palabra: 'serpiente', silabas: ['ser', 'pien', 'te'], emoji: '🐍', parecidas: ['sirena', 'sombrero', 'sandia'] },
  { id: 'sombrero', palabra: 'sombrero', silabas: ['som', 'bre', 'ro'], emoji: '🎩', parecidas: ['sirena', 'serpiente', 'sandia'] },
  { id: 'cereza', palabra: 'cereza', silabas: ['ce', 're', 'za'], emoji: '🍒', parecidas: ['sirena', 'serpiente', 'sombrero'] },
  { id: 'conejo', palabra: 'conejo', silabas: ['co', 'ne', 'jo'], emoji: '🐰', parecidas: ['cohete', 'corona', 'corazon'] },
  { id: 'cohete', palabra: 'cohete', silabas: ['co', 'he', 'te'], emoji: '🚀', parecidas: ['conejo', 'corona', 'corazon'] },
  { id: 'corona', palabra: 'corona', silabas: ['co', 'ro', 'na'], emoji: '👑', parecidas: ['conejo', 'cohete', 'corazon'] },
  { id: 'corazon', palabra: 'corazón', silabas: ['co', 'ra', 'zón'], emoji: '❤️', parecidas: ['corona', 'conejo', 'cohete'] },
  { id: 'paraguas', palabra: 'paraguas', silabas: ['pa', 'ra', 'guas'], emoji: '☂️', parecidas: ['paloma', 'pantalon', 'payaso'] },
  { id: 'paloma', palabra: 'paloma', silabas: ['pa', 'lo', 'ma'], emoji: '🕊️', parecidas: ['paraguas', 'pantalon', 'payaso'] },
  { id: 'pantalon', palabra: 'pantalón', silabas: ['pan', 'ta', 'lón'], emoji: '👖', parecidas: ['paloma', 'paraguas', 'payaso'] },
  { id: 'payaso', palabra: 'payaso', silabas: ['pa', 'ya', 'so'], emoji: '🤡', parecidas: ['paloma', 'paraguas', 'pantalon'] },
  { id: 'bicicleta', palabra: 'bicicleta', silabas: ['bi', 'ci', 'cle', 'ta'], emoji: '🚲', parecidas: ['ballena', 'bufanda'] },
  { id: 'ballena', palabra: 'ballena', silabas: ['ba', 'lle', 'na'], emoji: '🐋', parecidas: ['bicicleta', 'bufanda', 'caballo'] },
  { id: 'bufanda', palabra: 'bufanda', silabas: ['bu', 'fan', 'da'], emoji: '🧣', parecidas: ['ballena', 'bicicleta'] },
  { id: 'abeja', palabra: 'abeja', silabas: ['a', 'be', 'ja'], emoji: '🐝', parecidas: ['ardilla', 'arana', 'arcoiris'] },
  { id: 'ardilla', palabra: 'ardilla', silabas: ['ar', 'di', 'lla'], emoji: '🐿️', parecidas: ['abeja', 'arana', 'arcoiris'] },
  { id: 'arana', palabra: 'araña', silabas: ['a', 'ra', 'ña'], emoji: '🕷️', parecidas: ['ardilla', 'abeja', 'arcoiris'] },
  { id: 'arcoiris', palabra: 'arcoíris', silabas: ['ar', 'co', 'í', 'ris'], emoji: '🌈', parecidas: ['ardilla', 'arana', 'abeja'] },
  { id: 'dinosaurio', palabra: 'dinosaurio', silabas: ['di', 'no', 'sau', 'rio'], emoji: '🦕', parecidas: ['diamante'] },
  { id: 'diamante', palabra: 'diamante', silabas: ['dia', 'man', 'te'], emoji: '💎', parecidas: ['dinosaurio'] },
  { id: 'chocolate', palabra: 'chocolate', silabas: ['cho', 'co', 'la', 'te'], emoji: '🍫', parecidas: ['chinita', 'chaqueta'] },
  { id: 'chaqueta', palabra: 'chaqueta', silabas: ['cha', 'que', 'ta'], emoji: '🧥', parecidas: ['chocolate', 'chinita'] },
  { id: 'chinita', palabra: 'chinita', silabas: ['chi', 'ni', 'ta'], emoji: '🐞', parecidas: ['chocolate', 'chaqueta'] },
  { id: 'unicornio', palabra: 'unicornio', silabas: ['u', 'ni', 'cor', 'nio'], emoji: '🦄', parecidas: ['ardilla', 'abeja'] },
  { id: 'frutilla', palabra: 'frutilla', silabas: ['fru', 'ti', 'lla'], emoji: '🍓', parecidas: ['cereza', 'manzana'] },
];
