// (temporal) la Mascotienda: afuera, adentro, la ventana y los artículos; servidor dev en 5173
import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const out = process.argv[2]; mkdirSync(out, { recursive: true });
const b = await chromium.launch({ args: ['--enable-gpu', '--use-angle=d3d11', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1180, height: 820 } });
p.on('pageerror', e => console.log('ERR', e.message));
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE', m.text()); });
await p.addInitScript(() => localStorage.setItem('ciudadArcoiris.v2', JSON.stringify({ version: 2, cars: [], huesitos: 400,
  pets: [{ kind: 'perro', color: '#E9B77A', name: 'Toby' }, { kind: 'gato', color: '#FFFFFF', name: 'Nube' }] })));
await p.goto('http://localhost:5173/?test');
await p.waitForFunction(() => !document.querySelector('#btnPlay').disabled, null, { timeout: 60000 });
await p.click('#btnPlay');
const zona = () => p.evaluate(() => document.querySelector('#btnAction').hidden ? null : document.querySelector('#btnAction').textContent);
await p.evaluate(() => { window.__juego.teleport(20, 46); window.__juego.cam.yaw = Math.PI + 0.2; window.__juego.cam.dist = 16; });
await p.waitForTimeout(1500);
console.log('afuera:', await zona(), await p.locator('#placeName').textContent());
await p.screenshot({ path: `${out}/afuera.png` });
await p.locator('#btnAction').click({ force: true });
await p.waitForTimeout(1800);
console.log('adentro:', await p.locator('#placeName').textContent(), JSON.stringify(await p.evaluate(() => [window.__juego.player.pos.x, window.__juego.player.pos.z])));
await p.screenshot({ path: `${out}/adentro.png` });
// caminar hacia Robi
await p.keyboard.down('w'); await p.waitForTimeout(2500); await p.keyboard.up('w');
await p.waitForTimeout(600);
console.log('mostrador:', await zona());
await p.screenshot({ path: `${out}/robi.png` });
// pasillo de transporte
await p.evaluate(() => window.__juego.teleport(-2.4, 260.5));
await p.waitForTimeout(800);
console.log('pasillo:', await zona());
await p.locator('#btnAction').click({ force: true });
await p.waitForTimeout(800);
await p.screenshot({ path: `${out}/ventana.png` });
await p.locator('#tiendaBody [data-probar="globo"]').click();
await p.waitForTimeout(1200); await p.screenshot({ path: `${out}/probando_globo.png` });
await p.locator('#tiendaBody [data-comprar="patines"]').click();
await p.waitForTimeout(1200); await p.screenshot({ path: `${out}/compro_patines.png` });
await p.locator('#tiendaBody [data-leido]').click();
await p.locator('#tiendaTabs [data-sec="pociones"]').click();
await p.locator('#tiendaBody [data-comprar="arcoiris"]').click();
await p.locator('#tiendaBody [data-leido]').click();
await p.locator('#tiendaBody [data-pet="1"]').click();
await p.locator('#tiendaTabs [data-sec="accesorios"]').click();
await p.locator('#tiendaBody [data-comprar="alitas"]').click();
await p.waitForTimeout(1200); await p.screenshot({ path: `${out}/alitas_nube.png` });
await p.locator('#tiendaDone').click();
await p.waitForTimeout(800);
console.log('huesitos', await p.evaluate(() => window.__juego.player.huesitos), JSON.stringify(await p.evaluate(() => window.__juego.player.pets.map(m => m.extras))));
// salir y pasear con los artículos
await p.evaluate(() => window.__juego.teleport(0, 267.8));
await p.waitForTimeout(800); console.log('salida:', await zona());
await p.locator('#btnAction').click({ force: true });
await p.waitForTimeout(1500);
await p.keyboard.down('s'); await p.waitForTimeout(2200); await p.keyboard.up('s');
await p.evaluate(() => { window.__juego.cam.yaw = 0.8; window.__juego.cam.dist = 7; });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/calle.png` });
console.log('guardado', await p.evaluate(() => localStorage.getItem('ciudadArcoiris.v2').slice(0, 400)));
await b.close();
